### ISSUE TITLE
 Why does the first layer of the C-decoder also contain a Self-Attention module?

### ISSUE THREAD

**Issue by 1224wxwx** [huzhengdongcs/DAC-DETR#2]
Hi, thanks for sharing your great work! I downloaded your PyTorch code from Google Drive and noticed something weird in it. 

In deformable_transformer.py, lines 522-523 show that the queries for the C-decoder's first layer cross-attention have gone through self-attention first, as the figure below shows.

<img width="275" alt="co-de" src="https://github.com/huzhengdongcs/DAC-DETR/assets/17800557/8622b990-2b7e-445f-8eee-42b322cd9100">

Since the O-Decoder and C-Decoder share parameters, it seems like the same object queries' outputs are used for both one-to-one and one-to-many matching. This training method looks contradictory. Could you please take your time to clarify this? 

Thanks a lot!

**Comment by 1224wxwx** [comment]
> Thank you for your question. The purpose of the c-decoder is to eliminate the opposing impact that the self-attention in the subsequent layers may have on the cross-attention in the previous layer. Since there is no cross-attention before the first layer of self-attention, we maintain consistency with the o-decoder as much as possible while implementing the aforementioned function of the c-decoder. Therefore, we retained self-attention only in the first layer of the c-decoder (lid =0).
> 
> Regarding the second question, in the subsequent layers of the c-decoder, we have removed self-attention, so the query is influenced solely by cross-attention. In contrast, in the o-decoder, the query continues to be influenced by self-attention -> cross-attention -> self-attention.... As a result, there is a change in the output query from the c-decoder compared to the o-decoder.

Thank you for the reply! However, I still have doubts about the second question.

Since the first layer of both O-decoder and C-decoder is influenced by self-attention and cross-attention, their outputs at the first layer seem to be identical.  Due to the using of aux_loss, the identical predictions of the first layer are trained with the results of both one-to-one and one-to-many matching. So is there a contradiction in training the first layer in this way?

Looking forward to your reply.

**Comment by huzhengdongcs** [comment]
That's a good question. According to your descriprion, the first layer does exist. However, we found that the output and loss of the first layer in DETRs decoder are not very satisfactory. Therefore, we did not make any special attempts in this regard. I think this is an interesting question, and you might consider exploring it further in this area.
